ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.nexus.ApplicationKt.module ]
    }
}

auth0 {
    domain = "jav.eu.auth0.com"
    clientId = "iuLCUZA7QA6mw4w1vaIvCnF2OCisr89u"
    clientSecret = "PI7jOFI4UO8KUfaIDWzptd7wljVp5k_uuSsN546ZwWWBPunA2RkDszGbuVfJM6uj"
    audience = "https://jav.eu.auth0.com/api/v2/"
    callbackUrl = "http://localhost:8080/callback"
}