ktor {
    deployment {
        port = 8080
        # Esto permite que el servidor use un puerto distinto si se define en el sistema
        port = ${?PORT}
    }
    application {
        modules = [ com.nexus.ApplicationKt.module ]
    }
}

# Configuración unificada de Auth0
auth0 {
    domain = "https://jav.eu.auth0.com/"
    clientId = "iuLCUZA7QA6mw4w1vaIvCnF2OCisr89u"
    clientSecret = "PI7jOFI4UO8KUfaIDWzptd7wljVp5k_uuSsN546ZwWWBPunA2RkDszGbuVfJM6uj"
    audience = "https://jav.eu.auth0.com/api/v2/"
    callbackUrl = "http://localhost:8080/callback"
}

storage {
    # Asegúrate de que esta URI sea la que copiaste de MongoDB Atlas (botón 'Connect')
    uri = ${?MONGO_URI}
}